<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Resend" Version="0.2.2" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="17.2.2" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="17.2.2" />
  </ItemGroup>

</Project>
